version: '3'

services:

  mysql:

    image: mysql:5.7
    restart: always
    ports:
       - 3306:3306
    volumes:
       - mysql-data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql


volumes:
  
  wordpress-data:
  mysql-data:
